<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
            <div><p class="eyebrow">{{ match ($role) { 'provider' => 'Provider workspace', 'hospital' => 'Hospital workspace', 'admin' => 'Admin workspace', default => ($business->name ?? 'Business workspace') } }}</p><h1 class="page-title">Good morning, {{ Str::before(auth()->user()->name, ' ') }}.</h1><p class="page-subtitle">{{ match ($role) { 'provider' => 'Review opportunities and make informed funding decisions.', 'hospital' => 'Review approvals and keep intended use accountable.', 'admin' => 'Monitor activity across the CredAI funding network.', default => 'Your funding readiness, evidence, and next steps in one place.' } }}</p></div>
            <span class="status-pill status-pill--soft">{{ ucfirst($role) }} account</span>
        </div>
    </x-slot>

    <div class="dashboard-shell">
        @if(session('status'))<div class="workspace-status">{{ session('status') }}</div>@endif
        @if(session('error'))<div class="workspace-error">{{ session('error') }}</div>@endif
        <section class="hero-panel"><div class="hero-copy"><span class="eyebrow eyebrow--light">CredAI {{ $role }} desk</span><h2>{{ match ($role) { 'provider' => 'Find credible businesses ready for capital.', 'hospital' => 'Keep every approved use accountable.', 'admin' => 'See the whole funding network clearly.', default => 'Turn verified business activity into room to grow.' } }}</h2><p>{{ match ($role) { 'provider' => 'Review verified business activity, understand funding requests, and make confident decisions with a clear audit trail.', 'hospital' => 'Review intended use, approve eligible applications, and help funding reach the outcome it was designed to support.', 'admin' => 'Monitor businesses, providers, hospitals, payments, and the health of the CredAI funding network.', default => 'Track your evidence, connect with responsible fund providers, and keep hospital approvals moving in one calm workspace.' } }}</p>@if($role === 'business')<a href="{{ route('funding.create') }}" class="button button--light">Start an application <span aria-hidden="true">&rarr;</span></a>@else<a href="#application" class="button button--light">{{ $role === 'provider' ? 'Review opportunities' : ($role === 'hospital' ? 'Review approvals' : 'Open network overview') }} <span aria-hidden="true">&rarr;</span></a>@endif</div><div class="hero-orbit" aria-hidden="true"><div class="orbit-ring"></div><div class="orbit-core">30<small>%</small><span>minimum<br>activity</span></div><div class="orbit-tag orbit-tag--top">Verified flow</div><div class="orbit-tag orbit-tag--bottom">Built for trust</div></div></section>

        <section class="metric-grid" aria-label="Funding overview">
            <article class="metric-card"><span class="metric-label">Transaction activity</span><strong>{{ number_format($transactionTotal, 0) }} <small>{{ $business->currency ?? 'NGN' }}</small></strong><span class="metric-note">Across verified phone transactions</span></article>
            <article class="metric-card metric-card--accent"><span class="metric-label">Eligibility ratio</span><strong>{{ number_format($eligibilityRatio, 1) }}<small>%</small></strong><span class="metric-note">{{ $eligible ? 'You can request funding' : '30% needed to unlock funding' }}</span></article>
            <article class="metric-card"><span class="metric-label">Funding pipeline</span><strong>{{ $activeApplications }} <small>active</small></strong><span class="metric-note">{{ $approvedApplications }} approved applications</span></article>
            <article class="metric-card"><span class="metric-label">Trusted network</span><strong>{{ $providerCount + $hospitalCount }} <small>partners</small></strong><span class="metric-note">Providers and hospitals available</span></article>
        </section>

        <div class="content-grid">
            <section class="surface-card" id="application"><div class="section-heading"><div><span class="eyebrow">Your next move</span><h3>Funding readiness</h3></div><span class="status-pill {{ $eligible ? 'status-pill--green' : 'status-pill--amber' }}">{{ $eligible ? 'Ready to apply' : 'In progress' }}</span></div><div class="readiness-track"><span style="width: {{ min($eligibilityRatio, 100) }}%"></span></div><div class="readiness-labels"><span>0%</span><strong>{{ number_format($eligibilityRatio, 1) }}% captured</strong><span>30% target</span></div><div class="check-list"><div class="check-row {{ $business ? 'check-row--done' : '' }}"><span class="check-icon">{{ $business ? '✓' : '1' }}</span><div><strong>Register your business</strong><small>{{ $business ? 'Business profile is active' : 'Add your legal business and capital details' }}</small></div></div><div class="check-row {{ $transactionTotal > 0 ? 'check-row--done' : '' }}"><span class="check-icon">{{ $transactionTotal > 0 ? '✓' : '2' }}</span><div><strong>Connect transaction evidence</strong><small>{{ $transactionTotal > 0 ? 'Phone activity is being monitored' : 'Import phone number transaction history' }}</small></div></div><div class="check-row {{ $application?->hospital_approved_at ? 'check-row--done' : '' }}"><span class="check-icon">{{ $application?->hospital_approved_at ? '✓' : '3' }}</span><div><strong>Receive hospital approval</strong><small>{{ $application?->hospital_approved_at ? 'Approval is attached to your application' : 'A hospital validates the intended use of funds' }}</small></div></div></div>@if($role === 'business')<a href="{{ $eligible ? route('funding.create') : route('transactions.create') }}" class="button button--green">{{ $eligible ? 'Find a fund provider' : 'Add transaction evidence' }} <span aria-hidden="true">&rarr;</span></a>@endif</section>

            <section class="surface-card activity-card"><div class="section-heading"><div><span class="eyebrow">Live evidence</span><h3>Recent transactions</h3></div>@if($role === 'business')<div class="activity-actions"><form method="POST" action="{{ route('transactions.sync') }}">@csrf<button type="submit" class="text-button">Sync phone activity &rarr;</button></form><a href="{{ route('transactions.create') }}" class="text-button">Add manually &rarr;</a></div>@endif</div>@forelse ($transactions as $transaction)<div class="transaction-row"><span class="transaction-mark">+</span><div><strong>{{ $transaction->provider ?? 'Phone transaction' }}</strong><small>{{ $transaction->reference }} · {{ ucfirst($transaction->verification_status) }}</small></div><b>+{{ number_format($transaction->amount, 0) }}</b></div>@empty<div class="empty-state"><span class="empty-icon">+</span><strong>No verified activity yet</strong><p>Sync your phone activity or add a transaction to start building your readiness score.</p><a href="{{ route('transactions.create') }}" class="text-button">Add transaction evidence &rarr;</a></div>@endforelse</section>
        </div>

        <section class="partner-strip"><div><span class="eyebrow">One connected system</span><h3>Everyone sees the same source of truth.</h3></div><div class="partner-steps"><span><b>01</b> Business owner</span><i>&rarr;</i><span><b>02</b> Fund provider</span><i>&rarr;</i><span><b>03</b> Hospital approval</span></div></section>
    </div>
</x-app-layout>
