<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="CredAI connects people, insurers, and admins with smarter protection, mobile-money balance checks, and AI-assisted insurance decisions.">
    <title>CredAI | Smarter insurance decisions</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        :root { --c-ink: #12342d; --c-green: #16805a; --c-mint: #dff2c1; --c-lime: #c9ed77; --c-paper: #f7f8f3; --c-white: #fff; --c-muted: #6d8279; --c-line: #dbe6dc; --c-coral: #e4775e; }
        * { box-sizing: border-box; } html { scroll-behavior: smooth; } body { margin: 0; }
        .credai-home { background: var(--c-paper); color: var(--c-ink); font-family: 'Manrope', sans-serif; min-height: 100vh; overflow-x: clip; }
        .home-wrap { margin: auto; max-width: 1240px; padding-left: 28px; padding-right: 28px; }
        .language-switcher { align-items: center; border-left: 1px solid var(--c-line); display: flex; gap: 8px; margin-left: 4px; padding-left: 16px; }.language-switcher label { color: #81938a; font-size: .64rem; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }.language-switcher select { background: transparent; border: 0; color: var(--c-ink); cursor: pointer; font: 700 .7rem 'Manrope', sans-serif; outline: 0; padding: 4px 0; }
        .credai-home > header { background: rgba(247,248,243,.94); border-bottom: 1px solid rgba(219,230,220,.9); position: sticky; top: 0; z-index: 50; backdrop-filter: blur(14px); }
        .home-nav { align-items: center; display: flex; justify-content: space-between; padding-bottom: 24px; padding-top: 24px; }.logo { align-items: center; color: var(--c-ink); display: inline-flex; text-decoration: none; }.logo img { background: white; border: 2px solid var(--c-green); border-radius: 10px; box-shadow: 0 7px 18px rgba(18,52,45,.1); display: block; height: 58px; object-fit: contain; padding: 3px; width: 94px; }.footer-brand .logo img { height: 74px; width: 122px; }.logo-mark { align-items: center; background: var(--c-green); border-radius: 5px 5px 5px 0; color: white; display: inline-flex; font: 700 .78rem 'Manrope'; height: 29px; justify-content: center; width: 29px; }.home-nav-links { display: flex; gap: 29px; }.home-nav-links a, .home-login { color: #668077; font-size: .76rem; font-weight: 600; text-decoration: none; }.home-nav-links a:hover, .home-login:hover { color: var(--c-green); }.home-nav-actions { align-items: center; display: flex; gap: 17px; }.home-cta-small { background: var(--c-green); color: white; font-size: .74rem; font-weight: 700; padding: 11px 15px; text-decoration: none; }.home-cta-small:hover { background: var(--c-ink); }
        .hero { align-items: center; display: grid; gap: 73px; grid-template-columns: minmax(0, 1fr) 455px; padding-bottom: 82px; padding-top: 74px; }.hero-copy { max-width: 680px; }.kicker { color: var(--c-green); font-size: .67rem; font-weight: 700; letter-spacing: .16em; text-transform: uppercase; }.hero h1 { font: 600 clamp(3.15rem, 6.5vw, 6.35rem)/.9 'Manrope', sans-serif; letter-spacing: -.07em; margin: 18px 0 25px; }.hero h1 em { color: var(--c-green); font-style: normal; }.hero-description { color: var(--c-muted); font-size: 1rem; line-height: 1.75; margin: 0; max-width: 540px; }.hero-actions { align-items: center; display: flex; gap: 18px; margin-top: 29px; }.action-main, .action-quiet { align-items: center; display: inline-flex; font-size: .78rem; font-weight: 700; gap: 17px; padding: 15px 18px; text-decoration: none; }.action-main { background: var(--c-green); color: white; }.action-main:hover { background: var(--c-ink); }.action-quiet { border: 1px solid #b8cbbb; color: var(--c-ink); }.hero-footnote { color: #82958b; font-size: .69rem; margin-top: 15px; }
        .hero-art { background: var(--c-ink); min-height: 492px; overflow: hidden; padding: 29px; position: relative; }.hero-art:before { border: 1px solid rgba(201,237,119,.34); border-radius: 50%; content: ''; height: 505px; left: -180px; position: absolute; top: 78px; width: 505px; }.hero-art:after { background: var(--c-coral); border-radius: 50%; content: ''; height: 126px; opacity: .92; position: absolute; right: -38px; top: -38px; width: 126px; }.art-title { color: var(--c-lime); font-size: .64rem; font-weight: 700; letter-spacing: .15em; text-transform: uppercase; }.readiness-card { background: #f7faee; color: var(--c-ink); margin: 79px 0 0 28px; max-width: 316px; padding: 23px; position: relative; z-index: 1; }.readiness-card small { color: #71857a; display: block; font-size: .65rem; font-weight: 700; letter-spacing: .1em; text-transform: uppercase; }.readiness-card strong { display: block; font: 600 4.2rem/.93 'Manrope', sans-serif; letter-spacing: -.09em; margin: 13px 0 7px; }.readiness-card strong span { color: var(--c-green); font-size: 1.4rem; letter-spacing: 0; }.readiness-card p { color: #70847a; font-size: .71rem; line-height: 1.55; margin: 0; }.art-line { bottom: 29px; display: flex; gap: 10px; left: 29px; position: absolute; right: 29px; }.art-line span { border-top: 1px solid #47675b; color: #c4d7c8; flex: 1; font-size: .65rem; padding-top: 10px; }.art-line b { color: var(--c-lime); display: block; font-size: .61rem; margin-bottom: 5px; }
        .trust-bar { align-items: center; border-bottom: 1px solid var(--c-line); border-top: 1px solid var(--c-line); display: flex; justify-content: space-between; padding: 22px 0; }.trust-bar p { color: #7b8d84; font-size: .7rem; margin: 0; }.trust-points { display: flex; gap: 28px; }.trust-point { color: var(--c-ink); font: 600 .75rem 'Manrope', sans-serif; }.trust-point b { color: var(--c-green); font-size: 1.15rem; margin-right: 5px; }
        .section { padding: 110px 0 84px; }.section-top { align-items: flex-end; display: flex; justify-content: space-between; }.section-title { font: 600 clamp(2.2rem, 4.2vw, 3.8rem)/.98 'Manrope', sans-serif; letter-spacing: -.06em; margin: 12px 0 0; max-width: 590px; }.section-intro { color: var(--c-muted); line-height: 1.72; margin: 0; max-width: 315px; }
        .audience-grid { display: grid; gap: 12px; grid-template-columns: repeat(3, 1fr); margin-top: 50px; }.audience-card { background: var(--c-white); border: 1px solid var(--c-line); min-height: 315px; padding: 27px; position: relative; }.audience-card--dark { background: var(--c-ink); color: white; }.audience-card--mint { background: var(--c-mint); border-color: #c8dfb1; }.audience-number { color: var(--c-green); font: 700 .67rem 'Manrope'; }.audience-card h3 { font: 600 1.42rem/1.1 'Manrope', sans-serif; margin: 72px 0 12px; max-width: 220px; }.audience-card p { color: var(--c-muted); font-size: .77rem; line-height: 1.68; margin: 0; max-width: 255px; }.audience-card--dark p { color: #c0d3c5; }.audience-link { bottom: 27px; color: var(--c-green); font-size: .72rem; font-weight: 700; left: 27px; position: absolute; text-decoration: none; }
        .feature-band { background: var(--c-ink); color: white; margin: 12px 0 0; padding: 72px 55px; }.feature-layout { align-items: center; display: grid; gap: 80px; grid-template-columns: .82fr 1.18fr; }.feature-band .kicker { color: var(--c-lime); }.feature-band h2 { font: 600 clamp(2.1rem, 4.2vw, 3.8rem)/.98 'Manrope', sans-serif; letter-spacing: -.06em; margin: 13px 0 18px; }.feature-band p { color: #bfd2c4; font-size: .82rem; line-height: 1.75; max-width: 390px; }.feature-list { display: grid; gap: 0; grid-template-columns: repeat(2, 1fr); }.feature-item { border-top: 1px solid #3c5b50; padding: 22px 18px 22px 0; }.feature-item:nth-child(odd) { border-right: 1px solid #3c5b50; padding-right: 25px; }.feature-item:nth-child(even) { padding-left: 25px; }.feature-item b { color: var(--c-lime); display: block; font: 600 1.5rem 'Manrope'; margin-bottom: 8px; }.feature-item strong { display: block; font-size: .83rem; margin-bottom: 6px; }.feature-item span { color: #a8c0b0; display: block; font-size: .7rem; line-height: 1.55; }
        .process-section { padding-bottom: 110px; padding-top: 112px; }.process-grid { display: grid; gap: 12px; grid-template-columns: repeat(4, 1fr); margin-top: 49px; }.process-step { border-top: 2px solid var(--c-green); padding-top: 20px; }.process-step:nth-child(2) { border-color: var(--c-coral); }.process-step:nth-child(3) { border-color: #a8c95f; }.process-step:nth-child(4) { border-color: var(--c-ink); }.process-step b { color: var(--c-green); font: 700 .67rem 'Manrope'; }.process-step h3 { font: 600 1.06rem 'Manrope'; margin: 28px 0 8px; }.process-step p { color: var(--c-muted); font-size: .72rem; line-height: 1.65; margin: 0; max-width: 210px; }
        .cta-panel { align-items: center; background: var(--c-mint); border: 1px solid #c8dfb1; display: flex; justify-content: space-between; padding: 39px 44px; }.cta-panel h2 { font: 600 clamp(1.7rem, 3vw, 2.55rem)/1 'Manrope'; letter-spacing: -.05em; margin: 0 0 8px; }.cta-panel p { color: #668076; font-size: .76rem; margin: 0; }.cta-panel .action-main { flex-shrink: 0; }
        .home-footer { border-top: 1px solid var(--c-line); padding-top: 54px; }.footer-grid { display: grid; gap: 34px; grid-template-columns: 1.8fr repeat(3, 1fr); padding-bottom: 48px; }.footer-brand p { color: var(--c-muted); font-size: .75rem; line-height: 1.6; margin: 17px 0 19px; max-width: 205px; }.footer-brand a:not(.logo) { display: block; font-size: .74rem; font-weight: 600; margin-top: 9px; text-decoration: none; }.footer-phone { color: var(--c-green); }.footer-email { color: var(--c-ink); }.footer-column { display: flex; flex-direction: column; gap: 11px; }.footer-column strong { color: var(--c-ink); font: 600 .78rem 'Manrope'; margin-bottom: 7px; }.footer-column a, .footer-column span { color: #71857a; font-size: .73rem; text-decoration: none; }.footer-column a:hover { color: var(--c-green); }.footer-bottom { align-items: center; border-top: 1px solid var(--c-line); display: flex; justify-content: space-between; padding-bottom: 25px; padding-top: 20px; }.footer-bottom p, .footer-bottom span { color: #81938a; font-size: .68rem; margin: 0; }
        @media (max-width: 900px) { .home-nav-links { display: none; }.hero { gap: 45px; grid-template-columns: 1fr; }.hero-art { max-width: 540px; }.section-top { align-items: flex-start; flex-direction: column; gap: 22px; }.audience-grid { grid-template-columns: 1fr; }.audience-card { min-height: 270px; }.audience-card h3 { margin-top: 38px; }.feature-layout { gap: 45px; grid-template-columns: 1fr; }.process-grid { grid-template-columns: repeat(2, 1fr); row-gap: 35px; } }
        @media (max-width: 560px) { .home-wrap { padding-left: 18px; padding-right: 18px; }.home-login { display: none; }.language-switcher { border-left: 0; margin-left: 0; padding-left: 0; }.language-switcher label { display: none; }.home-cta-small { padding: 9px 11px; }.hero { padding-bottom: 62px; padding-top: 55px; }.hero h1 { font-size: clamp(3.25rem, 15vw, 5rem); }.hero-actions { align-items: stretch; flex-direction: column; max-width: 235px; }.hero-art { min-height: 380px; padding: 21px; }.readiness-card { margin-left: 0; margin-top: 72px; }.art-line { left: 21px; right: 21px; }.trust-bar { align-items: flex-start; flex-direction: column; gap: 17px; }.trust-points { flex-wrap: wrap; gap: 14px; }.section { padding: 77px 0 60px; }.feature-band { padding: 45px 24px; }.feature-list { grid-template-columns: 1fr; }.feature-item:nth-child(odd) { border-right: 0; padding-right: 0; }.feature-item:nth-child(even) { padding-left: 0; }.process-grid { grid-template-columns: 1fr; }.process-step h3 { margin-top: 16px; }.cta-panel { align-items: flex-start; flex-direction: column; gap: 25px; padding: 29px 23px; }.footer-grid { grid-template-columns: repeat(2, 1fr); padding-bottom: 33px; }.footer-brand { grid-column: 1 / -1; }.footer-bottom { align-items: flex-start; flex-direction: column; gap: 7px; } }
        .home-footer { background: var(--c-ink); border-top: 0; color: #f5faed; padding-top: 54px; }.home-footer .footer-brand p, .home-footer .footer-column a, .home-footer .footer-column span, .home-footer .footer-bottom p, .home-footer .footer-bottom span { color: #c5d8ca; }.home-footer .footer-column strong { color: var(--c-lime); }.home-footer .footer-phone, .home-footer .footer-email { color: white; }.home-footer .footer-column a:hover { color: var(--c-lime); }.home-footer .footer-bottom { border-top-color: rgba(223,242,193,.35); }.home-footer .logo img { border-color: var(--c-lime); box-shadow: 0 7px 18px rgba(0,0,0,.2); }
    </style>
        <style>
            :root { --c-ink: #143b32; --c-green: #167753; --c-mint: #e7f1d5; --c-lime: #c7e66a; --c-paper: #f4f7f2; --c-muted: #637a70; --c-line: #dce6dd; --c-coral: #d7775a; }
            .home-wrap { max-width: 1320px; }
            .home-nav { gap: 20px; min-height: 78px; padding-bottom: 14px; padding-top: 14px; position: relative; }
            .home-nav-links { align-items: center; gap: 23px; }
            .home-nav-links a, .home-login { color: #52695f; font-size: .78rem; }
            .home-nav-actions { gap: 12px; }
            .home-mobile-menu { display: none; }
            .home-mobile-menu summary { background: #fff; border: 1px solid var(--c-line); color: var(--c-ink); cursor: pointer; font-size: .74rem; font-weight: 700; list-style: none; padding: 10px 12px; }
            .home-mobile-menu summary::-webkit-details-marker { display: none; }
            .home-mobile-menu[open] summary { border-color: var(--c-green); }
            .home-mobile-menu-panel { background: #fff; border: 1px solid var(--c-line); box-shadow: 0 16px 36px rgba(20,59,50,.12); display: grid; min-width: 230px; padding: 7px; position: absolute; right: 0; top: calc(100% + 8px); z-index: 70; }
            .home-mobile-menu-panel a { border-bottom: 1px solid #edf2ec; color: #52695f; font-size: .82rem; font-weight: 600; padding: 12px 10px; text-decoration: none; }
            .home-mobile-menu-panel a:last-child { border-bottom: 0; }
            .home-mobile-menu-panel a:hover { background: #f4f7f2; color: var(--c-green); }
            .hero { gap: 64px; grid-template-columns: minmax(0, 1fr) minmax(380px, 455px); padding-bottom: 86px; padding-top: 82px; }
            .hero h1, .section-title, .feature-band h2, .cta-panel h2 { letter-spacing: 0; }
            .hero-copy .hero-description { color: #53695f; font-size: 1.04rem; line-height: 1.8; }
            .hero-footnote, .section-intro, .audience-card p, .process-step p { color: #5d7168; }
            .hero-art { background: linear-gradient(135deg, #10382f 0%, #174b3c 72%, #1b6047 100%); box-shadow: 0 22px 55px rgba(16,56,47,.16); }
            .hero-art:before { background: linear-gradient(rgba(199,230,106,.08) 1px, transparent 1px), linear-gradient(90deg, rgba(199,230,106,.08) 1px, transparent 1px); background-size: 42px 42px; border: 0; border-radius: 0; height: auto; inset: 0; left: 0; opacity: .55; pointer-events: none; top: 0; width: auto; }
            .readiness-card { border: 1px solid #e1eadd; border-radius: 8px; box-shadow: 0 18px 46px rgba(0,0,0,.12); }
            .trust-bar { border-color: #d4e0d6; }
            .trust-bar p { color: #5d7168; }
            .audience-card { border-radius: 8px; }
            .audience-card h3, .process-step h3 { letter-spacing: 0; }
            .logo img { background: transparent; border: 0; border-radius: 0; box-shadow: none; height: 48px; padding: 0; width: 174px; }
            .footer-brand .logo img { height: 48px; width: 174px; }
            .hero-art, .audience-card, .feature-band, .cta-panel { border-radius: 8px; }
            .hero-art:after { content: none; }
            .home-footer { padding-bottom: 88px; }
            .action-main, .action-quiet, .home-cta-small { border-radius: 5px; transition: background-color .18s ease, transform .18s ease; }
            .audience-card { transition: border-color .18s ease, transform .18s ease; }
            .audience-card:hover { border-color: #9fbea5; transform: translateY(-2px); }
            @media (max-width: 900px) {
                .home-nav-links { display: none; }
                .home-mobile-menu { display: block; }
                .home-nav { gap: 14px; }
                .home-nav-actions { margin-left: auto; }
                .hero { gap: 48px; grid-template-columns: 1fr; }
            }
            @media (max-width: 560px) {
                .home-nav { gap: 7px; padding-bottom: 10px; padding-top: 10px; }
                .home-mobile-menu summary { padding: 10px; }
                .home-mobile-menu-panel { left: 0; min-width: 0; right: 0; top: 100%; }
                .home-nav-actions { gap: 8px; }
                .home-cta-small { padding: 9px 10px; }
                .logo img, .footer-brand .logo img { height: 42px; width: 130px; }
                .hero { padding-bottom: 62px; padding-top: 50px; }
                .hero-copy .hero-description { font-size: .98rem; }
            }
        </style>
</head>
<body class="credai-home">
    <header class="home-wrap">
        <nav class="home-nav" aria-label="Main navigation">
            <a href="{{ url('/') }}" class="logo"><img src="{{ route('brand.logo') }}" alt="CredHealth - A CredAI Technologies Company"></a>
            <div class="home-nav-links"><a href="#platform">{{ __('Platform') }}</a><a href="#how-it-works">{{ __('How it works') }}</a><a href="#roles">{{ __('For providers') }}</a><a href="#roles">{{ __('For hospitals') }}</a><a href="{{ route('ai.index') }}">{{ __('AI guide') }}</a></div>
            <details class="home-mobile-menu">
                <summary>{{ __('Menu') }}</summary>
                <div class="home-mobile-menu-panel">
                    <a href="#platform">{{ __('Platform') }}</a>
                    <a href="#how-it-works">{{ __('How it works') }}</a>
                    <a href="#roles">{{ __('For providers') }}</a>
                    <a href="#roles">{{ __('For hospitals') }}</a>
                    <a href="{{ route('ai.index') }}">{{ __('AI guide') }}</a>
                </div>
            </details>
            <div class="home-nav-actions"><div class="language-switcher"><label for="language">{{ __('Language') }}</label><select id="language" onchange="window.location.href = this.value"><option value="{{ route('language.switch', 'en') }}" @selected(app()->getLocale() === 'en')>{{ __('English') }}</option><option value="{{ route('language.switch', 'sw') }}" @selected(app()->getLocale() === 'sw')>{{ __('Swahili') }}</option></select></div>@auth<a class="home-cta-small" href="{{ route('dashboard') }}">{{ __('Open dashboard') }}</a>@else<a class="home-login" href="{{ route('login') }}">{{ __('Log in') }}</a><a class="home-cta-small" href="{{ route('register') }}">{{ __('Get started') }}</a>@endauth</div>
        </nav>
    </header>

    <main class="home-wrap">
        <section class="hero">
            <div class="hero-copy"><span class="kicker">Protection built on real mobile value</span><h1>CredAI</h1><p class="hero-description">CredAI helps individuals, families, and insurance providers use mobile-money balance checks and AI recommendations to create fairer, smarter insurance decisions.</p><div class="hero-actions"><a class="action-main" href="{{ route('register') }}">Get my smart quote <span>&rarr;</span></a><a class="action-quiet" href="#how-it-works">Explore the platform</a></div><p class="hero-footnote">Coverage is matched to the balance available in the customer’s SIM account and the selected protection goal.</p></div>
            <div class="hero-art"><span class="art-title">CredAI protection index</span><div class="readiness-card"><small>Estimated monthly premium</small><strong>3,500<span>TZS</span></strong><p>Based on a healthy mobile balance and a family protection plan.</p></div><div class="art-line"><span><b>01</b>Balance check</span><span><b>02</b>AI review</span><span><b>03</b>Policy match</span></div></div>
        </section>

        <section class="trust-bar"><p>A connected protection system built around clarity, trust, and accountability.</p><div class="trust-points"><span class="trust-point"><b>01</b> SIM-based balance</span><span class="trust-point"><b>02</b> AI underwriting</span><span class="trust-point"><b>03</b> Faster policy decisions</span></div></section>

        <section class="section" id="roles"><div class="section-top"><div><span class="kicker">One platform, three roles</span><h2 class="section-title">Everyone sees the next right step.</h2></div><p class="section-intro">CredAI brings normal users, insurance providers, and admins into one secure protection flow with clear decision support.</p></div><div class="audience-grid"><article class="audience-card"><span class="audience-number">01 / NORMAL USER</span><h3>Protect what matters most.</h3><p>Check your SIM balance, explore affordable cover, and choose a plan that fits your real monthly value.</p><a class="audience-link" href="{{ route('register') }}">Create your profile &rarr;</a></article><article class="audience-card audience-card--dark"><span class="audience-number">02 / INSURANCE PROVIDER</span><h3>Price faster and smarter.</h3><p>Review customer risk, compare balance-backed eligiblity, and use AI suggestions to support underwriting.</p><a class="audience-link" href="{{ route('register') }}">Join as insurer &rarr;</a></article><article class="audience-card audience-card--mint"><span class="audience-number">03 / ADMIN</span><h3>Keep the network healthy.</h3><p>Monitor policies, control platform standards, and make sure every insurance decision stays transparent and compliant.</p><a class="audience-link" href="{{ route('register') }}">Open admin access &rarr;</a></article></div></section>

        <section class="feature-band" id="platform"><div class="feature-layout"><div><span class="kicker">The CredAI platform</span><h2>Smarter insurance decisions start with better evidence.</h2><p>From the first check to final approval, CredAI keeps customer data, balance insights, and policy recommendations in one secure system. That means better coverage matches for users and stronger oversight for providers and admins.</p><a class="action-main" href="{{ route('register') }}">See your protection fit <span>&rarr;</span></a></div><div class="feature-list"><div class="feature-item"><b>01</b><strong>SIM balance intelligence</strong><span>Use the live account value to guide safe premium and coverage decisions.</span></div><div class="feature-item"><b>02</b><strong>AI underwriting support</strong><span>Review before-and-after recommendations that explain the best-fit plan.</span></div><div class="feature-item"><b>03</b><strong>Provider review</strong><span>Help insurers evaluate risk with transparent customer data and account history.</span></div><div class="feature-item"><b>04</b><strong>Admin oversight</strong><span>Monitor system health, policy quality, and compliance from a single control layer.</span></div></div></div></section>

        <section class="process-section" id="how-it-works"><div class="section-top"><div><span class="kicker">How it works</span><h2 class="section-title">From SIM balance to secure cover.</h2></div><p class="section-intro">A simple process that helps people buy protection with confidence and helps providers price fairly.</p></div><div class="process-grid"><article class="process-step"><b>01 / CHECK</b><h3>Review the customer balance.</h3><p>Assess the real mobile-money balance that supports monthly premium capacity.</p></article><article class="process-step"><b>02 / PROFILE</b><h3>Match a protection goal.</h3><p>Choose a cover category such as family protection or health support.</p></article><article class="process-step"><b>03 / AI</b><h3>Receive a smart recommendation.</h3><p>CredAI suggests the right premium, risk level, and coverage value using a transparent model.</p></article><article class="process-step"><b>04 / APPROVE</b><h3>Issue the policy.</h3><p>Providers and admins review the final recommendation and move the policy forward with confidence.</p></article></div></section>

        <section class="cta-panel"><div><h2>Ready to build a smarter protection experience?</h2><p>Start with a live balance check, generate a quote, and see how AI can support fairer insurance.</p></div><a class="action-main" href="{{ route('register') }}">Get started free <span>&rarr;</span></a></section>
    </main>

    <footer class="home-footer"><div class="home-wrap footer-grid"><div class="footer-brand"><a href="{{ url('/') }}" class="logo"><img src="{{ route('brand.logo') }}" alt="CredHealth - A CredAI Technologies Company"></a><p>Verified activity. Responsible capital. Stronger businesses.</p><a class="footer-phone" href="tel:+255652455040">+255 652 455 040</a><a class="footer-email" href="mailto:hello@credai.co.tz">hello@credai.co.tz</a></div><div class="footer-column"><strong>Explore</strong><a href="#platform">{{ __('Platform') }}</a><a href="#how-it-works">{{ __('How it works') }}</a><a href="#roles">{{ __('For providers') }}</a><a href="#roles">{{ __('For hospitals') }}</a></div><div class="footer-column"><strong>{{ __('Support') }}</strong><a href="{{ route('login') }}">{{ __('Sign in') }}</a><a href="{{ route('register') }}">{{ __('Join the network') }}</a><a href="mailto:support@credai.co.tz">Help centre</a><a href="tel:+255652455040">{{ __('Contact') }}</a></div><div class="footer-column footer-location"><strong>Visit us</strong><span>CredAI Tanzania</span><span>Dar es Salaam, Tanzania</span><span>Mon - Fri, 08:00 - 17:00 EAT</span></div></div><div class="home-wrap footer-bottom"><p>&copy; {{ date('Y') }} credAI. Funding with a clearer conscience.</p><span>Built for trust across Tanzania</span></div></footer>
@include('shared.ai-assistant')
</body>
</html>
