<x-app-layout>
    <x-slot name="header"><div><p class="eyebrow">CredHealth business profile</p><h1 class="page-title">{{ $business ? 'Update your business profile' : 'Create your business profile' }}</h1></div></x-slot>
    <div class="form-shell"><div class="form-intro"><span class="eyebrow">Required before funding</span><h2>Build a clear profile for your business.</h2><p>Your capital and verified activity help CredHealth calculate a funding readiness score that providers can understand.</p></div><x-auth-session-status class="workspace-status" :status="session('status')" /><form method="POST" action="{{ route('business.store') }}" class="workspace-form">@csrf
        <div class="form-field"><label for="name">Business name</label><input id="name" name="name" type="text" value="{{ old('name', $business?->name) }}" required autofocus><x-input-error :messages="$errors->get('name')" /></div>
        <div class="form-row"><div class="form-field"><label for="sector">Business sector</label><input id="sector" name="sector" type="text" placeholder="Health, retail, agriculture..." value="{{ old('sector', $business?->sector) }}" required><x-input-error :messages="$errors->get('sector')" /></div><div class="form-field"><label for="registration_number">Registration number <span>(optional)</span></label><input id="registration_number" name="registration_number" type="text" value="{{ old('registration_number', $business?->registration_number) }}"></div></div>
        <div class="form-row"><div class="form-field"><label for="capital">Business capital</label><input id="capital" name="capital" type="number" min="0" step="0.01" value="{{ old('capital', $business?->capital) }}" required><x-input-error :messages="$errors->get('capital')" /></div><div class="form-field"><label for="currency">Currency</label><select id="currency" name="currency" required><option value="TZS" @selected(old('currency', $business?->currency ?? 'TZS') === 'TZS')>TZS — Tanzanian shilling</option><option value="NGN" @selected(old('currency', $business?->currency) === 'NGN')>NGN — Nigerian naira</option><option value="USD" @selected(old('currency', $business?->currency) === 'USD')>USD — US dollar</option></select></div></div>
        <div class="form-actions"><a href="{{ route('dashboard') }}" class="form-cancel">Cancel</a><button type="submit" class="button button--green">Save business profile <span>&rarr;</span></button></div>
    </form></div>
</x-app-layout>
